// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5pksHcQO6foYWEGy680-ifR43b55xo8Y',
    appId: '1:691853100347:web:d0cfbc55ae35374e06e31e',
    messagingSenderId: '691853100347',
    projectId: 'procedimentos-f1737',
    authDomain: 'procedimentos-f1737.firebaseapp.com',
    storageBucket: 'procedimentos-f1737.firebasestorage.app',
    measurementId: 'G-P8HHJ49E80',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjSq3hgnQD_atNBBD4himK5-mTabPw3_c',
    appId: '1:691853100347:android:4889d2211287231b06e31e',
    messagingSenderId: '691853100347',
    projectId: 'procedimentos-f1737',
    storageBucket: 'procedimentos-f1737.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6KGsx0_70c99j6cnS7AirAghK7cZcGXk',
    appId: '1:691853100347:ios:b7d02ef174cdfb9006e31e',
    messagingSenderId: '691853100347',
    projectId: 'procedimentos-f1737',
    storageBucket: 'procedimentos-f1737.firebasestorage.app',
    iosBundleId: 'com.example.procedimentos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6KGsx0_70c99j6cnS7AirAghK7cZcGXk',
    appId: '1:691853100347:ios:b7d02ef174cdfb9006e31e',
    messagingSenderId: '691853100347',
    projectId: 'procedimentos-f1737',
    storageBucket: 'procedimentos-f1737.firebasestorage.app',
    iosBundleId: 'com.example.procedimentos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5pksHcQO6foYWEGy680-ifR43b55xo8Y',
    appId: '1:691853100347:web:dbfda13d6410095106e31e',
    messagingSenderId: '691853100347',
    projectId: 'procedimentos-f1737',
    authDomain: 'procedimentos-f1737.firebaseapp.com',
    storageBucket: 'procedimentos-f1737.firebasestorage.app',
    measurementId: 'G-KNBT4D0WVW',
  );
}
